apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-5efo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-5efo
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-5efo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-5efo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-5efo
    spec:
      containers:
      - image: quay.io/qijing/release-e2e-pyxis-tenant/appstudio/dc-metro-map-5efo@sha256:697a52b7e9278e1b8c677d14bb6ed96d39cdc592e08518172a52b7f3ede75f90
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
